# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate search-provider

Name:           rust-search-provider
Version:        0.3.0
Release:        %autorelease
Summary:        Rust wrapper around the GNOME Shell search provider API

# Upstream license specification:  GPL-3.0-or-later
License:        GPL-3.0-or-later
URL:            https://crates.io/crates/search-provider
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Rust wrapper around the GNOME Shell search provider API.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gdk-pixbuf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gdk-pixbuf-devel %{_description}

This package contains library source intended for building other packages which
use the "gdk-pixbuf" feature of the "%{crate}" crate.

%files       -n %{name}+gdk-pixbuf-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pixbuf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pixbuf-devel %{_description}

This package contains library source intended for building other packages which
use the "pixbuf" feature of the "%{crate}" crate.

%files       -n %{name}+pixbuf-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
