# Generated by rust2rpm 22
%bcond_without check
%global debug_package %{nil}

%global crate favicon-scrapper

Name:           rust-favicon-scrapper
Version:        0.1.0
Release:        %autorelease
Summary:        Rust favicon scrapper

License:        MIT
URL:            https://gitlab.gnome.org/World/Authenticator/-/blob/master/favicon-scrapper
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21
BuildRequires:  pkgconfig(libadwaita-1) >= 1

%global _description %{expand:
Rust favicon scrapper.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
